### ISSUE TITLE
infra.aap_configuration Dispatch - Constructed Inventories Not Created Properly

### ISSUE THREAD

**Issue by daleroux** [redhat-cop/infra.aap_configuration#1050]
## Summary

The `infra.aap_configuration.dispatch` module does not create constructed inventories properly. Specifically, it skips any `limit` or `source` variables defined in the inventory resource file. As a result, the input inventory appears empty.

## Issue Type

- Bug Report

## Ansible, Collection, Controller details

infra.aap_configuration  
module: dispatch

## Steps to Reproduce
The issue can be reproduced on **AAP 2.5** with the following collection versions:

- **ansible-controller**: `4.6.9`
- **ansible-platform**: `2.5.20250312`
- **awx-awx**: `24.6.1`
- **infra-aap_configuration**: `3.1.0`
- **infra-eda_configuration**: `1.1.0`

### Version of ansible-core
```sh
ansible --version
ansible [core 2.17.3]
```

### Playbook Used
```yaml
- hosts: localhost
  connection: local
  gather_facts: false

  vars:
    # Format for 2.5
    aap_username: "your_login"
    aap_password: "your_password"
    aap_hostname: "URL_of_AAP2.5_environment"
    aap_validate_certs: false

  pre_tasks:
    - name: Include vars from controller_configs directory
      ansible.builtin.include_vars:
        dir: "opt/tower_backups/aap_casc_24_flattened"
        ignore_files: [controller_config.yml.template]
        extensions: ["yaml"]

  roles:
    # This is for 2.5
    - role: infra.aap_configuration.dispatch
      vars:
        gateway_configuration_dispatcher_roles:
          - role: gateway_organizations
            var: aap_organizations
            tags: organizations
            assign_galaxy_credentials_to_org: false
            assign_default_ee_to_org: false
            assign_notification_templates_to_org: false

        controller_configuration_dispatcher_roles:
          - role: controller_projects
            var: controller_projects
            tags: projects
          - role: controller_inventories
            var: controller_inventories
            tags: inventories
          - role: controller_inventory_sources
            var: controller_inventory_sources
            tags: inventory_sources
```

### How to Run the Playbook
```sh
ansible-playbook -vv dispatch_25.yml
```

## Expected Result
The constructed inventory should be created with all the defined `limit` and `source` variables from the inventory resource file as well as the source inventories.

## Actual Result
The constructed inventory gets created but is completely **empty**.

```

## STEPS TO REPRODUCE

<!--- Describe exactly how to reproduce the problem, using a minimal test-case -->

<!--- Paste example playbooks or commands between triple backticks below -->

```yaml (playbook/task)

```

```yaml (config/list/array/variables)

```
